stages:
  - test

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'

variables:
  MENDER_VERSION: master
  MENDER_ARTIFACT_VERSION: master

test:unit:
  stage: test
  needs: []
  image: alpine:latest
  before_script:
    - apk add --update git make curl python3
    - git submodule update --init --recursive
  script:
    - make test

test:integration:
  stage: test
  image: docker:18-dind
  tags:
    - mender-qa-slave
  before_script:
    - /usr/local/bin/dockerd-entrypoint.sh &
    - sleep 10
    - export DOCKER_HOST="unix:///var/run/docker.sock"
    - docker version
    - export
    # Install test dependencies
    - apk --update --no-cache add bash gcc make curl util-linux openssh
      python3 python3-dev libc-dev libffi-dev openssl-dev libc6-compat git
    - CRYPTOGRAPHY_DONT_BUILD_RUST=1 pip3 install -r tests/integration/requirements.txt
    - pip3 install docker-compose==1.24.0
    # Init the git submodules
    - git submodule update --init --recursive
    # Log in to the private Docker registry
    - docker login -u ${REGISTRY_MENDER_IO_USERNAME} -p ${REGISTRY_MENDER_IO_PASSWORD} registry.mender.io
    # Download and install mender-artifact
    - curl -f -O https://mender.s3.amazonaws.com/mender-artifact/$MENDER_ARTIFACT_VERSION/linux/mender-artifact
    - chmod ugo+x mender-artifact
    - mv mender-artifact /usr/bin/
  script:
    - cd tests/integration/
    - ./run.sh
