stages:
  - test

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'

test:unit:
  stage: test
  needs: []
  image: alpine:latest
  before_script:
    - apk add --update git make
    - git submodule update --init --recursive
  script:
    - make test
